# Generated by Django 3.1.1 on 2020-10-04 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, verbose_name='Phone')),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.shippingaddress', verbose_name='Shipping Address')),
                ('payment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.paymentmethod', verbose_name='Payment Method')),
                ('subscription', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.mealplan', verbose_name='Meal Plan')),
                ('web_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_user', to=settings.AUTH_USER_MODEL, verbose_name='Web User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
