CREATE TABLE item(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    UNIT VARCHAR(32)
);

CREATE TABLE ingredients(
    ID INT PRIMARY KEY NOT NULL,
    ITEM ITEM NOT NULL
);

CREATE TABLE meal_package(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    INGREDIENTS INGREDIENTS NOT NULL,
    PRICE INT NOT NULL,
    RECIPE MESSAGE_TEXT NOT NULL
);