# Generated by Django 3.1.1 on 2020-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_package',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meal_package',
            name='ingredients',
            field=models.ManyToManyField(to='meal_package.Ingredients'),
        ),
    ]
