# Generated by Django 3.1.1 on 2020-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_package', '0002_auto_20200914_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_package',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meal_package',
            name='ingredients',
            field=models.TextField(default='N/A'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
