# Generated by Django 3.1.1 on 2020-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200916_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
