# Generated by Django 3.1.1 on 2020-09-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200918_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='mealplan',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
