# Generated by Django 3.1.1 on 2020-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_lineitem_order_paymentmethod_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
