# Generated by Django 3.1.1 on 2020-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200918_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='CVV',
            field=models.CharField(max_length=4, verbose_name='Card Verification Value'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardnumber',
            field=models.CharField(max_length=16, verbose_name='Card number'),
        ),
    ]
