# Generated by Django 3.1.1 on 2020-09-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer'),
        ('cart', '0012_auto_20200918_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
